name: test

on:
  push:
    branches:
    - main
    tags:
    - "*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: internalpcfplatformautomation/ci:testing

    steps:
      - name: Checkout OM
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: om

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5
 
      - name: Test
        run: |
          go install github.com/onsi/ginkgo/ginkgo
          ginkgo -r -race -succinct -randomizeAllSpecs -randomizeSuites -keepGoing \
              -skipPackage acceptance,vmlifecyclecommands,vmmanagers \
              --covermode=atomic --coverprofile=../om-${{ github.sha }}-unit-test-code-coverage.out .

        working-directory: om
        env:
          CGO_ENABLED: 1

      - name: Archive Unit Test Code Coverage Output
        uses: actions/upload-artifact@v3
        with:
          name: Unit Test Code Coverage Output
          path: om-${{ github.sha }}-unit-test-code-coverage.out